// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -srcdir . -godefs /Users/zchee/go/src/github.com/fsnotify/fsevents/types_darwin.go

package fsevents

const (
	SizeofPtr	= 0x8
	SizeofShort	= 0x2
	SizeofInt	= 0x4
	SizeofLong	= 0x8
	SizeofLongLong	= 0x8
)

type (
	_C_short	int16
	_C_int		int32
	_C_long		int64
	_C_long_long	int64
)

type FSEventStream struct{}
